### ISSUE TITLE
trying to generate Interop for monaco editor 

### ISSUE THREAD

**Issue by QadiymStewart** [canhorn/EventHorizon.Blazor.Server.Interop#12]
https://github.com/microsoft/monaco-editor/blob/290a62d/website/typedoc/monaco.d.ts#L885

Trying to generate interop for the create function but GlobalShim is empty. 

/// Generated - Was not found in provided SourceFiles
/// Either add a Source File definition or update this file.
/// WARNING - Any Generation after updates will be lost.

using EventHorizon.Blazor.Server.Interop;

public class create : CachedEntity
{
    public create()
    {
    }

    public create(
        ICachedEntity entity
    )
    {
        this.___guid = entity.___guid;
    }
}

**Comment by canhorn** [comment]
Namespace functions are not currently supported. Tracking feature requests here: https://github.com/canhorn/EventHorizon.Blazor.TypeScript.Interop.Generator/issues/31
