### ISSUE TITLE
Ambiguity between 'App.JSRuntime' and 'App.JSRuntime'

### ISSUE THREAD

**Issue by ADefWebserver** [canhorn/EventHorizon.Blazor.Server.Interop#3]
The code works 👍🏾 But, in ".Blazor.Server.BabylonJS" are you aware of this warning?

![image](https://user-images.githubusercontent.com/1857799/90083596-dc3fe900-dcc7-11ea-95eb-f8ba06c017a6.png)

**Comment by canhorn** [comment]
Where is this exactly?
Do you have an partial backing class for App.razor?

**Comment by ADefWebserver** [comment]
This was in:
EventHorizon.Blazor.Interop.Generator\Sample\EventHorizon.Blazor.Server.BabylonJS\App.razor

However, after a reboot it went away.

Sorry for the false warning.
