### ISSUE TITLE
Is there a way I can get the code to generate the C# code I need for FollowCamera?

### ISSUE THREAD

**Issue by ADefWebserver** [canhorn/EventHorizon.Blazor.Server.Interop#4]
Is there a way I can get the code to generate the C# code I need for FollowCamera?
https://doc.babylonjs.com/api/classes/babylon.followcamera

I am trying to recreate this example:
https://playground.babylonjs.com/#5I2UKT

Thank You!

**Comment by canhorn** [comment]
Sure! I can generate the project with the FollowCamera.

If you need more APIs, and dont want to wait:
- Clone https://github.com/canhorn/EventHorizon.Blazor.Interop.Generator
- Navigate to Sample/EventHorizon.Blazor.Interop.Generator.ConsoleApp
- In Program.cs add any BabylonJS Classes/APIs you want to [this List](https://github.com/canhorn/EventHorizon.Blazor.Interop.Generator/blob/648812a7fa0509448f69063d7d131a90a3c7d272/Sample/EventHorizon.Blazor.Interop.Generator.ConsoleApp/Program.cs#L36)
- Running `dotnet run` will add/update the [EventHorizon.Blazor.BabylonJS.WASM](https://github.com/canhorn/EventHorizon.Blazor.Interop.Generator/tree/main/Sample/_generated/EventHorizon.Blazor.BabylonJS.WASM) project

**Comment by canhorn** [comment]
Updated https://github.com/canhorn/EventHorizon.Blazor.Interop.Generator

**Comment by ADefWebserver** [comment]
Yes, that worked.

![image](https://user-images.githubusercontent.com/1857799/92071630-1438ca00-ed64-11ea-97e2-e58a33756cef.png)

Amazing!
Thank You!
